// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fobyfercflxkwcsiliem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvYnlmZXJjZmx4a3djc2lsaWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MDIxMDEsImV4cCI6MjA4NzI3ODEwMX0.Qe7GJ1KdEdL0YjNOR8jjwz-TXI-9r72UT1L2vnZIlzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});