// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptdobbauqswdkormowly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZG9iYmF1cXN3ZGtvcm1vd2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMzYzMzcsImV4cCI6MjA3NTcxMjMzN30.t6IP6k0DLh1gSU0RlWjhJ209o9rTfVSo60Encd9U-EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});